### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by cubi7** [twstrike/coyim-page#4]
The SSL certificate for Coy.im expired 3 days ago

> coy.im uses an invalid security certificate. 
> The certificate expired on 11/14/2016 03:31 PM. The current time is 11/17/2016 12:09 PM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by olabini** [comment]
Thanks, we are aware and working on it. Sadly taking longer than it should. =(

**Comment by tcz001** [comment]
fixed
